---
- name: Install MariaDB, Nginx, PHP-FPM, Composer, Git, Vim and dos2unix
  hosts: 127.0.0.1
  remote_user: vagrant
  sudo: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - composer
    - git
    - dos2unix
    - vim
